### PR TITLE
Refactoring - removed friend field access.

### PR DESCRIPTION
**Pull request by vincentparrett**
Removed most friend usage of private fields. In most cases the friend access was not needed. Please review - lots of very small (1 letter) changes which should be harmless. One thing to look out for is if the change calls a prop setter that has side effects.. I tried to avoid those but may have missed some. I'll review again myself just in case.

### CODE REVIEW

**Review by joachimmarder — APPROVED** [review]

**Comment by vincentparrett** [comment]
Ok this should be good to go, I found two cases where side effects in setters were bypassed before so kept that behavior.

**Comment by joachimmarder** [comment]
I have to admit I find it challenging to review all those small 1.2k changes. But it looks good and I am now merging your PR.

**Comment by joachimmarder** [comment]
Thanks @vincentparrett  for this work! I'll check this week if our automated UI tests find anything unusual.

**Comment by vincentparrett** [comment]
Thanks. Now on to the next stage, extracting code out into units. I've made some good progress on this already.. but it's a big task.

**Review by joachimmarder — COMMENTED** [review]
@vincentparrett: Commit fcc324c caused bug that column header don't match the columns when scrolling horizontally. You can see it on this screenshot:
grafik

Please note that the first column is fixed.

**Comment by vincentparrett** [comment]
Ouch.. now that makes me wonder if there are any other getters like that. I'll review and see what I find.

**Pull request merged**
