### PR TITLE
SetData, like GetData should not force the "class" constraint on its parameter

### PR DESCRIPTION
**Pull request by obones**

### CODE REVIEW

**Comment by joachimmarder** [comment]
We may need to treat interfaces differently compared to classes, as far as I know the compiler does not do the automatic call to _AddRef() in this case. I need to carefully test this first.

**Comment by obones** [comment]
I believe it will call _AddRef because the pointer is cast to T and then the assignment is done.
But you are right, it needs to be tested with interfaces
I'm using it with enumeration members here, it works just fine.

**Comment by joachimmarder** [comment]
I will look into this mid of January, currently I don't have the time. Our TreeSize stores interfaces in the node data, and I will update my virtual TreeView and see if everything continues to work correctly.

**Comment by romankassebaum** [comment]
I just looked at one of my older projects. I'm using a record with interfaces for the tree data and I'm explicitly setting the references to nil in the OnFreeNode event handler. That's why I think that the compiler doesn't call _Release automatically.

**Comment by obones** [comment]
Here is a simple example: [generic setdata.zip](https://github.com/Virtual-TreeView/Virtual-TreeView/files/79531/generic.setdata.zip)

So yes, there is a need to have a "OnFreeNode" implementation to set the data back to nil, but that's pretty much it, no need to do any direct calls to _AddRef or _Release like whats done in TVirtualNode.SetData(IInterface)

However, we could go further and analyze T to see if it's a class or interface and add the appropriate flag in the node states. I'll try to do that and commit it if I succeed.

**Comment by obones** [comment]
Well, there it is in the latest commits.
The first one is to make sure that we don't call _Release on a nil instance and the second one makes the OnFreeNode implementation unnecessary.

**Comment by joachimmarder** [comment]
While revisiting this code I recognized one thing: When using the traditional, non-generic way via `TBaseVirtualTree.SetNodeData()` to set user data the flag `vsOnFreeNodeCallRequired` is set regardless of the type of the user data. 

With your pull request and when using `TVirtualNode.SetData<T>()` the flag vsOnFreeNodeCallRequired is set only if the type of the user data is a class.

Was this intended? Seems a little inconsistent to me. Under the premise that the OnFreeNode event is used _only_ for freeing the user data the `OnFreeNode` event does not need to fire if the user data is an interface. But what if it is a Pointer to a record? Without the class constraint  it would now be possible to call `SetData<T>()` that way.

**Comment by obones** [comment]
Yes, you are right, the code would be better that way:

```
procedure TVirtualNode.SetData<T>(pUserData: T);

begin
  T(Pointer((PByte(@(Self.Data))))^) := pUserData;
  case PTypeInfo(TypeInfo(T)).Kind of
    tkInterface:
      Include(Self.States, vsReleaseCallOnUserDataRequired);
    else
      Include(Self.States, vsOnFreeNodeCallRequired);
  end;
end;
```

This way it is consistent with the other `SetData`/`SetNodeData` methods where `vsOnFreeNodeCallRequired`is present for everything except interfaces.
However, I feel that even that last thing is not nice, and `vsOnFreeNodeCallRequired` should also be present in the interface case.

**Comment by joachimmarder** [comment]
> `vsOnFreeNodeCallRequired` should also be present in the interface case.

Agreed and changed accordingly.

**Pull request merged**
