### PR TITLE
Multiple selection by mouse and scrolling

### PR DESCRIPTION
**Pull request by crxbit**
When multiselect in Options.SelectionOptions no need to change focusednode in this place.

### CODE REVIEW

**Comment by joachimmarder** [comment]
Hi @crxbit, can you please explain your pull request? What is the undesired behavior that it fixes, and can this behavior be replicated?

**Comment by crxbit** [comment]
> Hi @crxbit, can you please explain your pull request? What is the undesired behavior that it fixes, and can this behavior be replicated?

Hi, Joachim, of course:

See video1:  https://recordit.co/riLLPVKCC4
See video2:  https://recordit.co/50vzeBTKLn

I made selection process in TVirtualStringTree by handling MouseMove event on it. 
I need option toMultiSelect in FOptions.SelectionOptions for multiple selection nodes. 
In video1 I move down mouse cursor out of bounds of Tree, but code 
FocusedNode := Node  does not allow scrolling down. 

But when I added condition:
(not (toMultiSelect in FOptions.SelectionOptions)) AND (SelectedCount = 1)

Scrolling behavior while mouse move event is ok even when mouse goes out of bounds of the tree.

See videos. Light blue cell - this is focused node (and column )), blue nodes - is selected only.
I made many selected columns in this frame myself (not in VTS).

**Comment by crxbit** [comment]
Selection process I made in OnChangeFocus event, but in MouseMove event I change FocusedNode for mouse.
I can attach these procedures for deep understanding if need...

**Comment by joachimmarder** [comment]
I made some tests `with the `toAutoScroll` option set and it worked as expected, see attached video.
GridDemo

A sample project would be truly appreciated. Instructions how to modify the `GridDemo` of the `Advanced` sample project are fine too.

**Comment by joachimmarder** [comment]
No response regarding repo steps for several months. I will not accept a PR if there is a true issue that can be replicated.

**Pull request closed without merging**
