### PR TITLE
- added: an option to block the painting operations while the scrolling is performed

### PR DESCRIPTION
**Pull request by Jeanmilost**
This option may increase the painting performances under certain condition, especially when the cells contain complex drawing operations.

### CODE REVIEW

**Comment by joachimmarder** [comment]
I tried your code but was unable to see any difference with or without the new option set. Can you please explain further?

**Comment by Jeanmilost** [comment]
Hello Joachin,

Thank you for your answer.

In fact the issue is about trees performing heavy drawing operations. I sent 2 videos showing the interface of the application I'm working on, one without the option enabled, the other with. See how the scrolling is bleeding when the option isn't enabled.

I'm available for further questions you may have.

Regards
________________________________
De : Joachim Marder <notifications@github.com>
Envoyé : jeudi, 15 novembre 2018 20:57
À : Virtual-TreeView/Virtual-TreeView
Cc : Jean-Milost Reymond; Author
Objet : Re: [Virtual-TreeView/Virtual-TreeView] - added: an option to block the painting operations while the scrolling is performed (#845)


I tried your code but was unable to see any difference with or without the new option set. Can you please explain further?

**Comment by joachimmarder** [comment]
Sorry, I but I do not seen any videos. Can you send a sample project or can one of the included sample projects be changed so that it shows the issue.

Virtual TreeView already has so many options that I am reluctant to add more if they are not truly of general interest.

**Comment by Jeanmilost** [comment]
Hello Joachim,

The issue that my new code is fixing appeared in a huge commercial project with a complex interface, which I'm not allowed to share. For that reason I did these videos, showing you the difference without and with the option enabled.

As you say that you not received the videos, I will attach them again. Please find them as attachments.

Regards
________________________________
De : Joachim Marder <notifications@github.com>
Envoyé : samedi, 17 novembre 2018 18:28
À : Virtual-TreeView/Virtual-TreeView
Cc : Jean-Milost Reymond; Author
Objet : Re: [Virtual-TreeView/Virtual-TreeView] - added: an option to block the painting operations while the scrolling is performed (#845)


Sorry, I but I do not seen any videos. Can you send a sample project or can one of the included sample projects be changed so that it shows the issue.

Virtual TreeView already has so many options that I am reluctant to add more if they are not truly of general interest.

**Comment by joachimmarder** [comment]
> The issue that my new code is fixing appeared in a huge commercial project with a complex interface, which I'm not allowed to share.

I don't expect you to share this project, but I was hoping that the problem could be illustrated in some sample project. Because I wonder: What sense does scrolling make if you don't see where you are scrolling to?

> As you say that you not received the videos

There are still no videos attached to the issue, please check yourself.

**Comment by Jeanmilost** [comment]
Hello Joachim,

Because I wonder: What sense does scrolling make if you don't see where you are scrolling to?
=> The idea here is absolutely not to stop the scrolling, but to synchronize its drawing. Currently, when the scrolling function is called, the drawing is done at the same time that the new position is recalculated, which gives this tearing effect. The code I added stops the drawing during the calculation of the new position, then sends a drawing command, by calling the Invalidate() function, after the new position has been calculated entirely. But as I said in my previous e-mail, this seems to pose several side effects that I found later. So I have to revise my code.

There are still no videos attached to the issue, please check yourself.
________________________________
De : Joachim Marder <notifications@github.com>
Envoyé : vendredi, 23 novembre 2018 11:10
À : Virtual-TreeView/Virtual-TreeView
Cc : Jean-Milost Reymond; Author
Objet : Re: [Virtual-TreeView/Virtual-TreeView] - added: an option to block the painting operations while the scrolling is performed (#845)


The issue that my new code is fixing appeared in a huge commercial project with a complex interface, which I'm not allowed to share.

I don't expect you to share this project, but I was hoping that the problem could be illustrated in some sample project. Because I wonder: What sense does scrolling make if you don't see where you are scrolling to?

As you say that you not received the videos

There are still no videos attached to the issue, please check yourself.

**Comment by joachimmarder** [comment]
>  as I said in my previous e-mail

I did not receive a mail. I am using the GitHub website to post comments, you should consider that too. It could work more reliable.

> this seems to pose several side effects that I found later. So I have to revise my code.

This is why I prefer to have sample projects or repro steps before I accept pull request. :-)

**Pull request closed without merging**
