### PR TITLE
New toBlockPaintWhileScroll option to remove the scroll glitches while intensive drawing

### PR DESCRIPTION
**Pull request by Jeanmilost**
This new option change nothing when drawing is few intensive. However, when the required painting to achieve a cell content become intensive, the scrolling may bleed. I joined a demo showing the issue. You may find it in the __NEW_OPTION_DEMO folder.

**NOTE** this demo isn't created to show a pretty content, but to illustrate the issue I face in several of my applications. On the left, you can see a virtual draw tree without the option activated, and on the right, the same tree with the option activated. If you perform intensive scrolling operation on the left tree, you will see it scroll with a pronounced tear effect. On the other hand the right tree will not tear. It may have a jerky effect, but it never tears.

I also added a timer to slow down the individual cell drawing (up to 100 ms), to allow to simulate what happen on drawing with different intensity. When set on 0ms, the tearing is very light, whereas it becomes very evident since 10-20ms. For your info several of my project may take a such time to draw the content of their cells.

**This is why that option is very important for my projects, because the tearing effect is sometimes very pronounced, and this option greatly reduces the problem.**

### CODE REVIEW

**Comment by joachimmarder** [comment]
I tried your sample project (C++ Buillder 10.2 Windows 10 1803), but I could not see any difference between the left and the right side. I verified using the debugger that the line of code with `LockWindowUpdate()` is passed.

> If you perform intensive scrolling operation on the left tree, you will see it scroll with a pronounced tear effect.

Can you please describe more exactly what I am supposed to see?

**Comment by Jeanmilost** [comment]
Hello Joachim,

Thank you for the the time you took to analyze my push request.

By testing on other computers, I narrowed the issue and why you can't reproduce it.

The issue is caused by slow painting while scrolling. That is, it appears when cell painting is slow. The scrolling is forcing the tree to repaint before finishing current paint which is causing the tearing /bleeding. Just like if you disable monitor VSync may cause similar issues. That's probably why you could not see the issue, it depends from your hardware configuration, paint and scroll relative times.

My fix is similar to turning ON VSync. I am not sure if its the best solution, or if it can be better fixed internally in your code for better performances.

You can reproduce the issue simply by clicking continuously the scroll down arrow button (visual button) and playing with the paint sleep value track bar, until you reproduce the issue on your machine.

Thank you for looking into the issue again.

Best regards,
Jean-Milost Reymond
________________________________
De : Joachim Marder <notifications@github.com>
Envoyé : dimanche, 3 mars 2019 09:16
À : Virtual-TreeView/Virtual-TreeView
Cc : Jean-Milost Reymond; Author
Objet : Re: [Virtual-TreeView/Virtual-TreeView] New toBlockPaintWhileScroll option to remove the scroll glitches while intensive drawing (#877)


I tried your sample project (C++ Buillder 10.2 Windows 10 1803), but I could not see any difference between the left and the right side. I verified using the debugger that the line of code with LockWindowUpdate() is passed.

If you perform intensive scrolling operation on the left tree, you will see it scroll with a pronounced tear effect.

Can you please describe more exactly what I am supposed to see?

**Comment by ValtsS** [comment]
I tried to backport your patch to my fork, I am experimenting with. But it did not work quite well in my case - seemed like when scrolling speed increases beyond certain limit it stops showing changes at all. It is possible that the issue is in my fork, as the code is not quite what is in the upstream.

As for VSync - VSync is enabled in any windows where desktop composition is running - which is a big majority.

**Comment by Jeanmilost** [comment]
Hello Joachim,

The VSync was just and a comparison with a similar effect in games, where the engine can disable VSync for higher frame rate and responsiveness.

My case is somewhat similar, but its a fight between paint and scrolling.

The issue I face in the virtual trees is similar to this one: https://stackoverflow.com/questions/32246132/winforms-layered-controls-with-background-images-cause-tearing-while-scrolling

Maybe this may serve to find a good solution to resolve this issue?

Best regards
________________________________
De : Valts Silaputnins <notifications@github.com>
Envoyé : vendredi, 8 mars 2019 15:36
À : Virtual-TreeView/Virtual-TreeView
Cc : Jean-Milost Reymond; Author
Objet : Re: [Virtual-TreeView/Virtual-TreeView] New toBlockPaintWhileScroll option to remove the scroll glitches while intensive drawing (#877)


I tried to backport your patch to my fork, I am experimenting with. But it did not work quite well in my case - seemed like when scrolling speed increases beyond certain limit it stops showing changes at all. It is possible that the issue is in my fork, as the code is not quite what is in the upstream.

As for VSync - VSync is enabled in any windows where desktop composition is running - which is a big majority.

**Comment by joachimmarder** [comment]
@Jeanmilost : The comment about VSync and that your patch is not working well was not from me, but from another VTV user. You should use the GitHub website for commenting instead of email, it provides more oversight.

> The issue I face in the virtual trees is similar to this one: https://stackoverflow.com/questions/32246132/winforms-layered-controls-with-background-images-cause-tearing-while-scrolling

Are you using a background image like in this case?

Please understand I am reluctant to accept a pull request  that caused problems before, for a problem that I cannot reproduce and that no one seems to have experienced before.

I have the impression that you are working on the symptoms here instead of addressing the root cause, which is the slow painting itself.

**Comment by Jeanmilost** [comment]
Anyway it's just an option, it is deactivated by default and users are free to enable it or not. In my case it is really useful, but it's true that the issue it resolves is unusual, and may seem useless or until wrong for the huge majority of standard users which generally perform a simple text painting. But I can guarantee that such issues may quickly appear when you perform intensive drawing, and when they appear, it's a painful way to fix them without a such above proposed option.

It's also true that the option may slow down the scrolling, and make it a little jerky, which is a inevitable side effect, but greatly acceptable in relation to the issue it fixes, at least in my case. 

Yes, I use a background image on several virtual trees, for which I implemented a drawing system which supports the transparency. However the tearing issue also appear on several trees where intensive paint are performed, e.g if my cells paint complex GDI+ drawing, images, ...

About the issue you mentioned in my code, it's true that my first version contained a bug, which I fixed since. So the issue you mention should no longer exists in the current version. At least I no longer noticed any recent problems while I use this code.

But finally, feel free to accept or reject my suggestion. It is really useful for me, and I think it may be useful for any eventual others users in my situation, but in case it is rejected I still can create my own inherited tree component, which will fix the issue for me.

Regards

**Comment by joachimmarder** [comment]
> Anyway it's just an option, it is deactivated by default and users are free to enable it or not

I know. VTV gathered a lot of such options in the past 20 years. And for some of them, I am not sure why they were introduced and if they still make sense. Still, the code for all those options has to be maintained, and sometimes I get bug reports because options do not work anymore or get in conflict with other options, which is more likely the more options you have.

This is why I want at least a proper repro project, which can be used later to verify code changes.

**Pull request closed without merging**
