### PR TITLE
Extracted Header, Columns, Options and others to new units.

### PR DESCRIPTION
**Pull request by vincentparrett**
Sorry it's a massive PR but there was no other way to make this sort of change. 

Marked as draft for now while I test.. would be good if others could [checkout this PR](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally) and test on their applications to see if I have messed up. 

My application (finalbuilder) makes extensive use of VT, but obviously I don't use every feature/property/event - it compiled with minor changes (adding VirtualTrees.Types to uses clause). 

TODO

- [x] Document any breaking changes
- [x] See if anything is broken as a result of these changes - I have compiled and tested with 3 applications that all used VT extensively - no issues found so far.
- [x] Decide what to do with Header.Tree and Columns.Header properties - Changed types.
- [x] Build with XE3-10.4.2 Win32/Win64 - no issues.

Breaking Changes (all minor)

- References to options enums requires adding VirtualTrees.Types to uses.
- TVTHeaderAddPopupItemEvent sender parameter changed to TObject  (due to circular references). 
- TVTHeader.TreeView property changed to TCustomControl (due to circular references).
- TVirtualTreeColumns.TreeView property changed to TCustomControl (due to circular references).
- TVTHeaderPopup - TColumnChangeEvent Sender parameter changed to TObject.
- TVirtualDrawTree moved to VirtualTrees.DrawTree

If this is going to be merged it's best done sooner rather than later - the extraction to units makes merging changes in from master more and more difficult.

### CODE REVIEW

**Comment by joachimmarder** [comment]
I found two cases that cause a breaking change beyond adding `VirtualTrees.Types` to the uses clause:

- Move enum `TSmartAutoFitType` from unit `VirtualTrees.Header` would fix the first one and seems more consistent.
- Accessing TVirtualTreeColumns.Header.Treeview.GetCurrentPPI` no longer compiles. Merging 'VirtualTrees.Columns` in unit `VirtualTrees.Header` would allow strong typing of the `Header` property.

**Comment by joachimmarder** [comment]
> TODO: Document any breaking changes

I started here:
https://github.com/JAM-Software/Virtual-TreeView/wiki/Breaking-changes-in-upcoming-release

**Comment by vincentparrett** [comment]
Is there anything else I need to do for this PR?

**Comment by joachimmarder** [comment]
> Is there anything else I need to do for this PR?

No. I was just very busy in the past weeks and was thinking about making a V7.6 release before merging the pull request. We currently have [11 fixed issues](https://github.com/JAM-Software/Virtual-TreeView/issues?q=is%3Aclosed+milestone%3AV7.6).

**Comment by vincentparrett** [comment]
> No. I was just very busy in the past weeks and was thinking about making a V7.6 release before merging the pull request. We currently have [11 fixed issues](https://github.com/JAM-Software/Virtual-TreeView/issues?q=is%3Aclosed+milestone%3AV7.6).

Ok no worries.. good idea to release the other fixes before merging.

**Comment by joachimmarder** [comment]
Hi @vincentparrett, I created a new branch "V7_stable" and just created a release based on this branch. I would now be ready to accept the pull request in the master branch.

**Comment by joachimmarder** [comment]
@vincentparrett, the PR has a conflict. Would you mind checking if this can be easily resolved in your fork, so that I can auto-merge the PR? Thanks!

**Comment by vincentparrett** [comment]
Should be ok now.

**Pull request merged**
