### PR TITLE
Cppbuilder

### PR DESCRIPTION
**Pull request by zencode1**
C++Builder packages for 10.4 and 11.  I started by copying the CBuilder 10.X project files and modified in the IDE for both.  Here are the notable differences from the 10.X files:
- Added all of the new .pas files which were missing from 10.X
- Removed the use of pre-compiled headers
- Removed incremental linking
- Edited the library paths to place destination binary files in `$(Platform)\$(Config)`
- Removed the `<Excluded_Packages>` section
- Removed the `<Deployment>` section

### CODE REVIEW

**Comment by zencode1** [comment]
I noticed the .bpi, .lib, and .a files weren't being generated.  I added an explicit path for `<BPILibOutputDir>` and force-pushed.

**Comment by joachimmarder** [comment]
I just merged your other commit to the master branch, I saw this PR too late.

**Comment by zencode1** [comment]
@joachimmarder since #1177 was merged to `master` I'll redo just the differences in a new PR.

How would you like to handle these sorts of conflicting changes in the future?  The way I did it with separate branches and PRs or the way it happened here with a change to the stable branch first, followed by a merge to master, and then the additional changes?

**Comment by joachimmarder** [comment]
I would prefer PR for each branch, just as you did it. But typically that does not happen, and so I merge (or cherry-pick) those commits. I just saw your second PR too late. Any chance that you send it again?

**Comment by zencode1** [comment]
@joachimmarder Sure thing.  I created PR #1180 with just the differences from this old PR.  I will perform two new PRs in the near future (one for V7_stable and one for master) to create the missing C++Builder compiler version projects.

**Comment by joachimmarder** [comment]
Thank you very much, @zencode1 .

**Pull request closed without merging**
