### PR TITLE
Add ColumnHeaderSpanning event

### PR DESCRIPTION
**Pull request by Npc8**
Let app decide how many columns can be spanned.

### CODE REVIEW

**Comment by joachimmarder** [comment]
Thank you for the pull request. Can you please elaborate a little more on this feature? Do you have some screenshots that illustrate what it does?

**Comment by Npc8** [comment]
This is a bit like Merge Cells in Excel,
screenshot-20241208-141551

**Comment by joachimmarder** [comment]
OK, I accepted the pull request. 

Is there any chance that you send a pull request with a demo project for this feature? Or one that extends one of the existing sample projects?

**Comment by Npc8** [comment]
> OK, I accepted the pull request.
> 
> Is there any chance that you send a pull request with a demo project for this feature? Or one that extends one of the existing sample projects?

I have already updated the GridDemo and made a new pull request.

**Pull request merged**
